OBilet.UI/Controllers/HomeController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Caching.Memory;
using Microsoft.Extensions.Logging;
using OBilet.Domain.Entities.Location;
using OBilet.Domain.Entities.Session;
using OBilet.Infrastructure.Abstract;
using OBilet.UI.Helpers;
using OBilet.UI.Models;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Wangkanai.Detection;

namespace OBilet.UI.Controllers
{
    public class HomeController : Controller
    {
        private IMemoryCache _memCache;
        private readonly IObiletService _obiletService;
        private static IHttpContextAccessor _contextAccessor;
        private readonly IBrowserResolver _detection;
        private readonly string _ipAdress;

        public HomeController(IObiletService obiletService, IMemoryCache memCache, IHttpContextAccessor contextAccessor, IBrowserResolver detection)
        {
            _obiletService = obiletService;
            _memCache = memCache;
            _contextAccessor = contextAccessor;
            _detection = detection;
            _ipAdress = _contextAccessor.HttpContext.Connection.RemoteIpAddress.ToString();

        }

        [HttpGet]
        public IActionResult Index(BusLocationViewModel model)
        {
            var sessionInfo = SessionData();
            if (sessionInfo.IsSuccess)
            {
                BusLocationRequestModel busLocationRequest = new BusLocationRequestModel()
                {
                    DeviceSession = sessionInfo.Data,
                    Date = DateTime.Now,
                    Language = "tr-TR",
                };

                var locationList = _obiletService.GetBusLocation(busLocationRequest);
                if (locationList.Success)
                {
                    model.BusLocationList = locationList.Data;
                    model.IsSuccess = true;
                    model.ErrorMessage = locationList.Message;
                }
                else
                {
                    model.IsSuccess = false;
                    model.ErrorMessage = locationList.Message;
                }
            }
            else
            {
                model.ErrorMessage = "Session didn't create";
                model.IsSuccess = false;
            }
            return View(model);
        }

        [HttpGet]
        public RequestViewModel<SessionResponseModel> SessionData()
        {
            RequestViewModel<SessionResponseModel> model = new RequestViewModel<SessionResponseModel>();

            var sessionData = new SessionResponseModel();
            if (!_memCache.TryGetValue(_ipAdress, out sessionData))
            {
                SessionRequestModel request = new SessionRequestModel()
                {
                    BrowserName = _detection.Browser.Type.ToString(),
                    BrowserVersion = _detection.Browser.Version.ToString(),
                    IpAdress = _ipAdress,
                    Port = _contextAccessor.HttpContext.Connection.RemotePort.ToString(),
                    Type = 7,
                };
                var result = _obiletService.GetSession(request);
                sessionData = result.Data;
                if (result.Success)
                {
                    CacheHelper.SetKey<SessionResponseModel>(_ipAdress, result.Data, _memCache);
                    model.Data = sessionData;
                    model.IsSuccess = true;
                    return model;
                }
                else
                {
                    model.IsSuccess = false;
                    model.Message = result.Message;
                    return model;

                }
            }
            else
            {
                model.Data = CacheHelper.GetKey<SessionResponseModel>(_ipAdress, _memCache);
                model.IsSuccess = model.Data != null ? true : false;
                return model;

            }


        }
        public IActionResult Search(string Search)
        {
            var sessinoInfo = CacheHelper.GetKey<SessionResponseModel>(_ipAdress, _memCache);
            BusLocationRequestModel busLocationRequest = new BusLocationRequestModel()
            {
                DeviceSession = sessinoInfo,
                Date = DateTime.Now,
                Language = "tr-TR",
                Data = Search

            };
            var locationList = _obiletService.GetBusLocation(busLocationRequest);
            StringBuilder data = new StringBuilder();

            if (locationList.Success)
            {
                foreach (var item in locationList.Data)
                {
                    data.Append("<option value=" + item.Id + "> " + item.Name + "</option>");
                }
                return Json(new
                {
                    result = true,
                    message = "Success",
                    Object = data,
                });
            }
            return Json(new
            {
                result = false,
                message = "Failed",
                Object = data,
            });
        }



    }
}

OBilet.UI/Controllers/JourneyController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Caching.Memory;
using OBilet.Domain.Entities.Journey;
using OBilet.Domain.Entities.Session;
using OBilet.Infrastructure.Abstract;
using OBilet.UI.Helpers;
using OBilet.UI.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace OBilet.UI.Controllers
{
    public class JourneyController : Controller
    {
        private IMemoryCache _memCache;
        private readonly IObiletService _obiletService;
        private readonly string _ipAdress;
        private static IHttpContextAccessor _contextAccessor;

        public JourneyController(IObiletService obiletService, IHttpContextAccessor contextAccessor, IMemoryCache memCache)
        {
            _obiletService = obiletService;
            _contextAccessor = contextAccessor;
            _ipAdress = _contextAccessor.HttpContext.Connection.RemoteIpAddress.ToString();
            _memCache = memCache;

        }

        [HttpPost]
        public IActionResult Index(int fromBusLocationId, int toBusLocationId, DateTime date)
        {
            List<JourneyDetailModel> journeyDetailList = new List<JourneyDetailModel>();
            var request = new JourneyRequestModel()
            {
                DepartDate = date,
                ToBusLocation = fromBusLocationId,
                FromBusLocation = toBusLocationId,
                DeviceSession = CacheHelper.GetKey<SessionResponseModel>(_ipAdress, _memCache),
                Language = "tr-TR"
            };

            var result = _obiletService.GetJourneys(request);
            foreach (var item in result.Data)
            {

                var resultData = new JourneyDetailModel
                {
                    Origin = item.Origin,
                    Arrical = item.Arrival.ToString(),
                    Price = item.Price.ToString(),
                    Destination = item.Destination,
                    Departure = item.Departure,
                    JourneyId = (int)item.Id,
                    OriginLocation = item.OriginLocation,
                    DestinationLocation = item.DestinationLocation,
                    PriceType = item.PriceType,

                };

                journeyDetailList.Add(resultData);
            }

            return View(journeyDetailList);
        }


        public IActionResult Detail()
        {
            JourneyDetailModel journeyDetailList = new JourneyDetailModel();
          

            return View(journeyDetailList);
        }

    }
}

OBilet.UI/Views/Home/Index.cshtml
@model BusLocationViewModel
<style>
    .bootstrap-select {
        width: 100% !important;
    }

    .btnn {
        background-color: gray;
        border: none;
        color: white;
        font-size: 15px;
        cursor: pointer;
        border-radius: 25px;
    }

    #txtDate {
        background: url('images/calendar.gif') no-repeat;
        border: 1px solid #ccc;
        height: 18px;
        width: 100px;
        padding-left: 25px;
    }
</style>

<div class="container">
    <div class="row">
        <div class="col-lg-3"></div>
        <div class="col-lg-6">
            <div class="card">
                <div class="card-body">
                    <form method="post" enctype="multipart/form-data" asp-controller="Journey" asp-action="Index" class="card-body">
                        <div class="row">
                            <div class="col-lg-1">
                                <i class="fa fa-location-arrow"></i>

                            </div>
                            <div class="col-lg-11">
                                <select class="form-control cities" name="fromBusLocationId" id="fromBusLocationId" title="İl veya ilçe adı yazın">
                                    @if (Model.BusLocationList != null && Model.BusLocationList.Count > 0)
                                    {
                        @foreach (var item in Model.BusLocationList)
                        {
                            if (Model.FromCity.HasValue && Model.FromCity.Value == item.Id)
                            {
        <option value=@item.Id selected="">@item.Name</option>
 }
    else
    {
<option value=@item.Id>@item.Name</option>
}

}}
                                </select>
                                <label class="frombuslocationvalidation" style="display:none">Şehir alanı seçmelisiniz...</label>

                                <br />
                            </div>
                        </div>

                        <div style="margin-left: 85% "><button type="button" class="btn btnn btn-sm " id="swap" style=" margin-top: 0;margin-bottom:0">&nbsp;<i class="fa  fa-arrows-v"></i>&nbsp;</button></div>

                        <div class="row">
                            <div class="col-lg-1">
                                <i class="fa fa-location-arrow"></i>

                            </div>
                            <div class="col-lg-11">
                                <select class="form-control cities" name="toBusLocationId" id="toBusLocationId" title="İl veya ilçe adı yazın">

                                    @if (Model.BusLocationList != null && Model.BusLocationList.Count > 0)
                                    {
                        @foreach (var item in Model.BusLocationList)
                        {
                            if (Model.ToCity.HasValue && Model.ToCity.Value == item.Id)
                            {
        <option value=@item.Id selected="">@item.Name</option> }
                            else
                            {
        <option value=@item.Id>@item.Name</option>}

                        }}
                                </select>

                                <label class="tobuslocationvalidation" style="display:none">Şehir alanı seçmelisiniz...</label>
                            </div>


                        </div>
                        <br />
                        <div class="row">
                            <div class="col-lg-9">
                                <div style="width : 100%">
                                    <i class="fa fa-calendar"></i>
                                    <input type="text" name="date" id="date" class="datePicker" required />
                                </div>
                            </div>

                            <div class="col-lg-3">
                                <button type="button" class="btn btn-outline-dark btn-sm" id="today" style="margin-bottom: 2px; padding-top: 1px; padding-bottom: 1px;">Bugün</button><br />
                                <button type="button" class="btn btn-outline-dark btn-sm" id="tomorrow" style=" padding-top: 1px; padding-bottom: 1px;">&nbsp;Yarın&nbsp;&nbsp;</button>
                            </div>
                        </div>
                        <button type="submit" class="btn btn-primary btn-block" id="FoundTickets" style=" margin: 10px;">Bileti Bul</button>
                        <p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat. Duis autem vel eum iriure dolor in hendrerit in</p>
                    </form>
                </div>
            </div>
        </div>
        <div class="col-lg-4"></div>
    </div>
</div>
<script>
    $(document).ready(function () {
        var date = new Date();

        $('.datePicker').datepicker({
            clearBtn: false,
            format: "dd.mm.yyyy",
            startDate: new Date(),
            autoclose: true
        });
        $('.datePicker').datepicker('setDate', date);
        $('#today').css("background-color", "grey");
        $('#tomorrow').css("background-color", "white");

        $('#today').on('click', function () {
            $('.datePicker').datepicker('setDate', date);
            $('#today').css("background-color", "grey");
            $('#tomorrow').css("background-color", "white");

        });

        $('#tomorrow').on('click', function () {
            $('.datePicker').datepicker('setDate', new Date(date.getFullYear(), date.getMonth(), (date.getDate() + 1)));

            $('#today').css("background-color", "white");
            $('#tomorrow').css("background-color", "grey");

        });

        $('#swap').on('click', function () {
            debugger;

            var co=$("#fromBusLocationId").val();
            $("#fromBusLocationId").val($("#toBusLocationId").val());
            $("#toBusLocationId").val(co);

          
        });

        $('.cities').on('change', function () {
            debugger
            if ($("#fromBusLocationId").val() == $("#toBusLocationId").val()) {
              alert("Kalkış ve varış noktaları aynı olamaz");
                $('#FoundTickets').attr('disabled', 'disabled');
            }
            else {
                $('#FoundTickets').removeAttr('disabled');
            }


        });

        $('#fromBusLocationId').on('loaded.bs.select', function (e, clickedIndex, isSelected, previousValue) {
            $(".fromBusLocationId .bs-searchbox input").on('keyup', function () {


                var search = $(this).val();


                $.ajax({
                    url: 'Home/Search',
                    type: 'POST',
                    dataType: 'json',
                    data: { 'Search': search },
                    success: function (data) {

                        $('#fromBusLocationId').html(data.object).selectpicker('refresh');
                    }
                });
            });
        });

        $('#toBusLocationId').on('loaded.bs.select', function (e, clickedIndex, isSelected, previousValue) {
            $(".toBusLocationId .bs-searchbox input").on('keyup', function () {
                var search = $(this).val();
                $.ajax({
                    url: 'Home/Search',
                    type: 'POST',
                    dataType: 'json',
                    data: { 'Search': search },
                    success: function (data) {

                        $('#toBusLocationId').html(data.object).selectpicker('refresh');
                    }
                });
            });
        });


        $("#submit").click(function () {
            debugger;
            var a = $("#fromBusLocationId option:selected").val();
            var b = $("#toBusLocationId option:selected").val();
            if (a == "" && b == "") {
                $("#frombuslocationvalidation").show();
                $("#tobuslocationvalidation").show();
                return false;
            }
            else if (a == "") {
                $("#frombuslocationvalidation").show();
                $("#tobuslocationvalidation").hide();
                return false;
            }
            else if (b == "") {
                $("#tobuslocationvalidation").show();
                $("#frombuslocationvalidation").hide();
                return false;
            }
        });
    });
</script>